enum DefaultsKey {
    static let editorFontSize = "editorFontSize"
    static let editorLineSpacing = "editorLineSpacing"
    static let autoSaveEnabled = "autoSaveEnabled"
    static let spellCheckEnabled = "spellCheckEnabled"
    static let autoPairEnabled = "autoPairEnabled"
    static let newPostFormat = "newPostFormat"
    static let imagePasteLocation = "imagePasteLocation"
    static let imagePasteFormat = "imagePasteFormat"
    static let imagePasteJPEGQuality = "imagePasteJPEGQuality"
    static let imagePasteMaxDimension = "imagePasteMaxDimension"
    static let imagePasteNamingStrategy = "imagePasteNamingStrategy"
    static let selectedTheme = "selectedTheme"
    static let autoRenameOnSave = "autoRenameOnSave"
    static let addAliasOnRename = "addAliasOnRename"
    static let hugoExecutablePath = "hugoExecutablePath"
    static let showFrontmatterInspector = "showFrontmatterInspector"
    static let showOutline = "showOutline"
    static let focusMode = "focusMode"
    static let typewriterMode = "typewriterMode"
    static let sessionCurrentPost = "hugora.session.currentPost"
    static let workspaceBookmark = "hugora.workspace.bookmark"
    static let workspaceRecent = "hugora.workspace.recent"
    static let workspacePreferences = "hugora.workspace.preferences"
}
